# Generated by Django 3.0 on 2019-12-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='latitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coach',
            name='longitud',
            field=models.FloatField(),
        ),
    ]
